---
- name: Seting up required users and directories
  hosts: all
  become: yes
  tasks:
    - name: Creating prometheus and node_exporter users
      ansible.builtin.user:
        name: "{{ item }}"
        create_home: false
        shell: /bin/false # this will not allow the users to login into the user created ( if the user tries to login to this created user /bin/false will be executed which will exit from the shell immediately )
      loop:
        - prometheus
        - node_exporter
    - name: Create directory /etc/prometheus and /var/lib/prometheus
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
    - name: Make prometheus as owner of the directories
      ansible.builtin.file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

- name: Downloading prometheus
  hosts: all
  become: yes
  tasks:
    - name: Download Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.49.0-rc.1/prometheus-2.49.0-rc.1.linux-amd64.tar.gz
        dest: .
        checksum: sha256:af8488aeef92707fb0d3ede092208e67de37e51155d08f6ae7566d75278e87a6
    - name: Unarchive the file
      ansible.builtin.unarchive:
        src: prometheus-2.49.0-rc.1.linux-amd64.tar.gz
        dest: ./
        remote_src: yes
    - name: Copying prometheus and promtool binaries to local bin
      ansible.builtin.copy:
        src: "{{ item }}"
        dest:  /usr/local/bin/
        remote_src: yes
      loop:
        - prometheus-2.49.0-rc.1.linux-amd64/prometheus
        - prometheus-2.49.0-rc.1.linux-amd64/promtool
    - name: Make prometheus as owner of the binaries
      ansible.builtin.file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
      loop:
        - /usr/local/bin/prometheus
        - /usr/local/bin/promtool
    - name: Copying console and console_libraries to /etc/prometheus
      ansible.builtin.copy:
        src: "{{ item }}"
        dest:  /etc/prometheus
        remote_src: yes
      loop:
        - prometheus-2.49.0-rc.1.linux-amd64/consoles
        - prometheus-2.49.0-rc.1.linux-amd64/console_libraries 
    - name: Make prometheus as owner of the directories
      ansible.builtin.file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus/consoles
        - /etc/prometheus/console_libraries
    - name: Removing the files not needed
      ansible.builtin.file:
        path: prometheus-2.49.0-rc.1.linux-amd64
        state: absent
- name: Configuring Prometheus files
  hosts: all
  become: yes
  tasks:
    - name: Overwriting the config file of prometheus
      ansible.builtin.copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yaml
    - name: Setting OwnerShip
      ansible.builtin.file:
        path: /etc/prometheus/prometheus.yaml
        owner: prometheus
        group: prometheus
      
- name: Downloading node_exporter
  hosts: all
  become: yes
  tasks:
    - name: Downloading node node_exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: .
        checksum: sha256:a550cd5c05f760b7934a2d0afad66d2e92e681482f5f57a917465b1fba3b02a6
    - name: Unarchive the file
      ansible.builtin.unarchive:
        src: node_exporter-1.7.0.linux-amd64.tar.gz
        dest: ./
        remote_src: yes
    - name: Copying node exporter to local/bin
      ansible.builtin.copy:
        src: node_exporter-1.7.0.linux-amd64/node_exporter
        dest:  /usr/local/bin/
        remote_src: yes
    - name: Make node exporter as owner of the binaries
      ansible.builtin.file:
        path: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
    - name: Removing the files not needed
      ansible.builtin.file:
        path: node_exporter-1.7.0.linux-amd64
        state: absent
    - name: Configuring the systemd service file for node_exporter
      ansible.builtin.copy:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
- name: Running Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Starting prometheus
      ansible.builtin.command:
        cmd: /usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
      async: 1000
      poll: 0
    - name: Configuring the systemd service file for prometheus
      ansible.builtin.copy:
        src: prometheus.service
        dest: /etc/systemd/system/prometheus.service
    - name: Reloading daemon to re read the systemd configs
      systemd:
        daemon_reload: true
    - name: Starting prometheus and node_exporter
      systemd:
        state: started
        name: "{{ item }}"
      loop:
        - prometheus
        - node_exporter
    - name: Checking Output
      shell: systemctl status prometheus | grep active
      register: monit_status
    - debug: msg={{monit_status.stdout_lines}}

